version: '3'

services:
  web:
    build: .
    ports:
      - "80:5000"  # Map to port 80 for HTTP access
    volumes:
      - ./public:/app/public
      - ./resource:/app/resource
    environment:
      - FLASK_ENV=production
    restart: always

networks:
  default:
    driver: bridge